version: "3"
services:
  app:
    container_name: test-node
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src/app:/app
    working_dir: /app
    command: bash -c "npm run build && npm run start"
    tty: true
    ports:
      - 80:8080
