version: "3"
services:
  app:
    container_name: test-node
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src/app:/app
    working_dir: /app
    command: npm run dev
    tty: true
    ports:
      - 3000:3000
